LLAMA_API = "https://stock.cmcts.ai/c-agent/api/v1/prediction/dd0f9487-4ab8-4dc6-8b16-b665e3121499"
CLAUDE_API = "https://stock.cmcts.ai/c-agent/api/v1/prediction/bb99269d-6f89-414e-8702-5d84c5f8e1a4"
GRADER_API = "https://stock.cmcts.ai/c-agent/api/v1/prediction/d6675cbc-88a6-4ca4-8f1a-cf660a60beb8"
LANGFUSE_PUBLIC_KEY = "pk-lf-9c1bbc22-8180-4c1e-9d1c-4bedf12c56fc"
LANGFUSE_SECRET_KEY = "sk-lf-d758beb3-be26-4e22-9f7b-847bd9142d2b"